; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp8285]
platform = espressif8266
board = esp8285
framework = arduino
board_build.flash_mode = dout   ; <--- DO NOT LEAVE THIS OUT
monitor_speed = 57600           ; Set this to match your code's Serial.begin
upload_speed = 115200           ; High speed for faster flashing
